-- Alocucoes managed by the administrator.

CREATE TABLE IF NOT EXISTS public.alocucoes (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  body_pt TEXT NOT NULL DEFAULT '',
  body_en TEXT NOT NULL DEFAULT '',
  body_es TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS alocucoes_active_sort_idx
  ON public.alocucoes (is_active, sort_order, title);

ALTER TABLE public.alocucoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can view active alocucoes" ON public.alocucoes;
CREATE POLICY "Authenticated users can view active alocucoes"
  ON public.alocucoes FOR SELECT
  TO authenticated
  USING (is_active = TRUE);

INSERT INTO public.alocucoes (id, title, body_pt, body_en, body_es, sort_order)
VALUES
  ('alocucao-2', '4.1 DURANTE O EMBARQUE', 'Bem-vindos a bordo do voo GOL número _______ com destino a _______ com escala(s) em _______ e conexões. Se estiver sentado em uma saída de emergência, você pode ser solicitado a operá-la. Caso não se sinta à vontade, fale com um dos comissários. Power banks são proibidos nos compartimentos superiores e devem ser acomodados no bolsão ou em sua bagagem abaixo do assento a frente.

Assento livre a partir da fileira 6: Excepcionalmente neste voo, você pode escolher o seu assento a partir da fileira 6, exceto nas saídas de emergência.

Assento 100% Livre: Excepcionalmente neste voo, os assentos são de sua livre escolha.

Realizar quantas vezes forem necessárias: Sua ajuda é essencial para finalizarmos o embarque com maior agilidade. Conforme orientações de Embarque, lembramos que independentemente da quantidade de volumes, é obrigatória a acomodação de bolsa, mochila ou sacola abaixo do assento à sua frente, inclusive nas saídas de emergência, deixando livre o acesso ao corredor. Compartimentos superiores deverão ser utilizados somente para a acomodação de bagagens maiores, como mala de rodinhas.', 'Welcome aboard GOL flight number _____ with service to _____ and connections. If you are sitting by an emergency exit, you may be asked to operate it. If you don''t feel comfortable, talk to one of the flight attendants. Power banks are prohibited in overhead compartments and must be stowed in the seat pocket or in carry-on baggage placed under the seat in front of you.

Assento livre a partir da fileira 6: On this flight, you can choose your seat from row 6 on, except for emergency exit rows.

Assento 100% Livre: This is a free seating flight.

Realizar quantas vezes forem necessárias: Your help is essential for a faster boarding. As pre boarding instructions, regardless of the number of carry-on items, it is required to stow your purse, backpack, or bag under the seat in front of you, including at emergency exits, leaving free access to the aisle. Overhead compartments should only be used for larger baggage, such as suitcases.', 'Bienvenidos a bordo del vuelo GOL número _____ a _____ (nome da cidade) y escala(s) en _____ (nome(s) da(s) cidade(s)) y conexiones. Si está sentado en una salida de emergencia, es posible que le pidan que la maneje. Si no te sientes cómodo, habla con uno de los tripulantes de cabina. Los power banks están prohibidos en los compartimientos superiores y deben ser alojados en el bolsillo del asiento o en el equipaje de mano colocado debajo del asiento delantero.

Assentos livres a partir da fileira 6: Excepcionalmente en este vuelo podrás elegir tu asiento desde la fila 6, exceptuando en las salidas de emergencia.

Assentos 100% livres: Excepcionalmente en este vuelo los asientos son de libre elección.

Realizar quantas vezes forem necessárias: Su ayuda es esencial para que finalicemos el embarque más rápidamente. Según orientaciones de embarque, independientemente del número de volúmenes, es obligatorio acomodar bolsos, mochilas y bolsas debajo del asiento frente a usted, incluso en las salidas de emergencia, dejando libre el acceso al pasillo. Los compartimentos superiores sólo deben usarse para el alojamiento de equipaje más grande, como maletas con ruedas.', 10),
  ('alocucao-3', '4.2 REMANEJAMENTO DE PASSAGEIROS A BORDO', 'Por motivos operacionais, pedimos que _______ ($n^{\circ}$ de passageiros) clientes sentados nas fileiras _______ e/a _______ mudem para as fileiras _______ e/a _______. Obrigado(a).', 'For operational reasons, we would like to ask _______ ($n^{\circ}$ de passageiros) passengers seated in rows _______ and/through \_\_\_\_\_\_\_ to move to rows _______ and/through _______ Thank you!', 'Por razones operacionales, solicitamos que _______ (número de passageiros) clientes sentado en las filas _______ y/a _______ ocupen los asiento en las filas _______ y/a _______. ¡Gracias!', 20),
  ('alocucao-4', '4.3 SOLICITAÇÃO DE DESEMBARQUE VOLUNTÁRIO', 'Prezados Clientes, por motivos operacionais, precisamos de _______ ($n^{\circ}$ de passageiros) voluntários que possam seguir viagem em um próximo voo. Aqueles que aceitem desembarcar, por favor, identifiquem-se através da chamada de comissários. Nossa equipe do aeroporto dará mais informações e todo o suporte necessário. Obrigado(a).', 'Dear costumers, for operational reasons, we need _______ ($n^{\circ}$ de passageiros) volunteers who can travel on a next flight. Those who accept to disembark, please identify themselves by calling the flight attendants. Our airport team will give you more information and all the support you need. Thank you.', 'Estimados clientes, por razones operacionales, necesitamos _______ (nº de passageiros) voluntarios que puedan continuar su viaje en un próximo vuelo. Quienes acepten desembarcar, favor identificarse mediante la llamada de tripulantes. Nuestro personal de aeropuerto le proporcionará más informaciones y todo el apoyo necesario. ¡Gracias!', 30),
  ('alocucao-5', '4.4 ATRASO NA DECOLAGEM COM DESEMBARQUE', 'Devido a _______ (motivo do atraso) pedimos, por gentileza, que desembarquem com todos os seus objetos pessoais.

Quando houver o tempo estimado de retorno: O novo embarque está previsto para _______ ($h/min$). Se precisar de ajuda, conte conosco. Obrigado(a).', 'Due to _______ (motivo do atraso), we kindly request that you deplane with all your belongings.

Quando houver o tempo estimado de retorno: Boarding is now scheduled for \_\_\_\_\_\_\_ ($h/min$). If you have any questions, please talk to one of our flight attendants. Thank you.', 'Debido a _______ (motivo do atraso) les rogamos desembarcar con todos tus objetos personales.

Quando estiver o tempo estimado de retorno: El nuevo embarque está programado para _______ (h/min). Si necesitas ayuda, cuenta con nosotros. ¡Gracias!', 40),
  ('alocucao-6', '4.5 EMBARQUE ENCERRADO', 'Embarque encerrado! Este é o voo GOL _______ com destino a _______ (nome da cidade) e escala(s) em _______ (nome(s) da(s) cidade(s)) e conexões.', 'Boarding completed! This is GOL flight _____ with service to _____ and connections.', 'Embarque finalizado. Este es el vuelo GOL número _____ a _____ (nome da cidade) y escala(s) en _____ (nome(s) da(s) cidade(s)) y conexiones.', 50),
  ('alocucao-7', '4.5.1 GOL+ Conforto - Voos Domésticos', 'Os assentos GOL+ Conforto, localizados nas fileiras de 1 a _______ (última fileira GOL+ Conforto) e saídas de emergência, são de uso exclusivo dos clientes que adquiriram o produto antes do voo.', '', '', 60),
  ('alocucao-8', '4.5.2 Premium Economy e GOL+ Conforto - Voos Internacionais', 'A Premium Economy, localizada nas fileiras de 1 a 5 e os assentos GOL+ Conforto localizados nas saídas de emergência, são de uso exclusivo dos clientes que adquiriram o produto antes do voo. Em sua próxima viagem, dê um upgrade na sua experiência em voar GOL!', 'The Premium Economy seats, located in rows one to five and the GOL + Conforto seats located in the emergency exits are exclusive for customers who purchased the product before the flight! On your next trip, upgrade your experience of flying GOL!', 'Los asientos Premium economy, en las filas de 1 a 5 y los asientos Gol+ Conforto en las salidas de emergencia, son exclusivos para los clientes que adquirieron el produto antes del vuelo. En su próximo viaje, haga un "upgrade" en su experiencia en volar GOL.', 70),
  ('alocucao-9', '4.6 FECHAMENTO DE PORTAS', 'Antes do horário previsto: Confirmando nosso compromisso em valorizar o seu tempo, fechamos as portas antes do horário previsto. Para decolarmos, permaneça sentado, com seu cinto afivelado.

No horário previsto: Confirmando nosso compromisso em valorizar o seu tempo, fechamos as portas no horário previsto. Para decolarmos, permaneça sentado, com seu cinto afivelado.

Após o horário previsto: As portas foram fechadas. Para decolarmos, permaneça sentado, com seu cinto afivelado.', 'Antes do horário previsto: Confirming our commitment to always value your time, we have closed the doors ahead of schedule. For take-off, remain seated with your seatbelt fastened.

No horário previsto: Confirming our commitment to always value your time, we have closed the doors on schedule. For take-off, remain seated with your seatbelt fastened.

Após o horário previsto: All doors are now closed. For take-off, remain seated with your seatbelt fastened.', 'Antes do horário previsto: Confirmando nuestro compromiso de valorar su tiempo, cerramos las puertas antes de la hora programada. Para el despegue, permanezca sentado, con el cinturón abrochado.

No horário previsto: Confirmando nuestro compromiso de valorar su tiempo, cerramos las puertas en el tiempo programado. Para el despegue, permanezca sentado, con el cinturón abrochado.

Após o horário previsto: Las puertas están cerradas. Para el despegue, permanezca sentado, con el cinturón abrochado.', 80),
  ('alocucao-10', '4.6.1 Complementação da alocução Fechamento de Portas', 'A partir de agora, deixe os equipamentos eletrônicos em modo avião. O uso de power banks não é permitido durante todo o voo. É proibido fumar a bordo, inclusive cigarros eletrônicos. Para seu conforto, se necessário ajuste a saída de ar acima de seu assento.', 'From now on, please keep your electronic devices in airplane mode. The use of power banks is prohibited during the entire flight. Smoking is not allowed on board, including electronic cigarettes. For your comfort, please adjust the air vent above your seat if necessary.', 'A partir de ahora, deje los equipos electrónicos en modo avión. El uso de power banks no está permitido durante todo el vuelo. Está prohibido fumar a bordo, incluyendo cigarrillos electrónicos. Para su comodidad, si necesario ajuste la salida de aire arriba de su asiento.', 90),
  ('alocucao-11', '4.7 DESINSETIZAÇÃO DA AERONAVE (quando aplicável)', 'Por recomendação da Organização Mundial da Saúde, vamos desinsetizar a aeronave. O produto não faz mal à saúde.', 'As recommended by the World Health Organization, we will spray the aircraft for disinsection. This product is not harmful to your health.', 'Según lo recomendado por la Organización Mundial de la Salud, desinsectaremos la aeronave. Este producto no es perjudicial para la salud.', 100),
  ('alocucao-12', '4.8 AGLOMERAÇÃO PRÓXIMO AOS LAVATÓRIOS E COCKPIT - DESTINO EUA', 'Por determinação das autoridades dos Estados Unidos, é proibida a concentração de pessoas próximas aos toaletes e cabine de comando durante o Voo.', 'By determination of U.S. authorities, crowding close to the lavatories and cockpit during the flight is prohibited.', 'Por determinación de las autoridades estadounidenses, la aglomeración cerca de los baños y de la cabina de vuelo es prohibido durante el vuelo.', 110),
  ('alocucao-13', '4.9 BOAS-VINDAS TODOS OS VOOS', 'Olá! Meu nome é _______ (nome de guerra) _______ (Chefe de Cabine/Comissário(a)) deste voo e, em nome do(s) Comandante(s) _______ (nome(s) de guerra), dou boas-vindas a todos a bordo do Boeing 737- (700/800 / MAX 8), para o voo GOL _______ (número do voo) com destino a _______ (nome da cidade) (e escala(s) em _______ (nome da(s) cidade(s)) em parceria com a Air France, KLM e American Airlines (demais empresas, quando aplicável). Gostaria de estender uma saudação especial aos nossos clientes Smiles Magno, Diamante e Ouro. É uma alegria recebê-los novamente conosco. Nosso voo terá a duração de (tempo de voo).

Aeronaves com USB/Tomada: Pedimos que desconecte o seu equipamento eletrônico da (tomada/USB).

Aeronaves com USB/Tomada/Ped Holder: Pedimos que desconecte seu equipamento eletrônico da (tomada/USB) e feche o suporte da poltrona.', 'Hi! My name is (nome de guerra) (purser/flight attendant) of this flight, and on behalf of Captain(s) (nome de guerra) I welcome you aboard the Boeing 737- (700/800/MAX8), for GOL flight (número do voo) with service to (nome da cidade) (and connection(s) in) in partnership with Air France, KLM and American Airlines. We would like to extend a special welcome to our Smiles Magno, Diamante, and Ouro customers. It''s a pleasure to have you back on board with us. Our flight will last (tempo de voo).

Aeronaves com USB/Tomada: We request that you unplug your electronic devices from the (outlet/USB port).

Aeronaves com USB/Tomada/Ped Holder: We request that you unplug your electronic devices from the (outlet/USB port) and close the ped holder.', '¡Hola! Mi documento de identidad es (jefe de cabina/ uno de los(as) tripulantes de este vuelo) y en nombre del(a) capitán (nome do Comandante) doy la bienvenida a bordo del Boeing 737 (700/800/ MAX 8) para el vuelo GOL con destino a (nome da cidade) y escala(s) em (nome(s) da(s) cidade(s)) en asociación con Air France, KLM y American Airlines. Queremos dar una cordial bienvenida especial a nuestros clientes Smiles Magno, Diamante y Ouro. Es un placer tenerlos nuevamente a bordo con nosotros. Nuestro vuelo tendrá la duración de (tempo de voo).

Aeronaves com USB/Tomada: Desconecte su aparato electrónico del (enchufe/USB).

Aeronaves com USB/Tomada/Ped Holder: Desconecte su aparato electrónico del (enchufe/USB) y cierre el soporte.', 120),
  ('alocucao-14', '4.10 ANTES DA DECOLAGEM - VOOS DOMÉSTICOS', 'Vamos nos preparar para a decolagem! Deixe o encosto da sua poltrona na posição vertical e sua mesa fechada e travada. Fique atento aos avisos luminosos para afivelar seu cinto. Você poderá abrir o compartimento de bagagens quando esse aviso estiver apagado. É proibido fumar no avião e também impedir ou tentar impedir o funcionamento dos detectores de fumaça dos toaletes. Agora vamos demonstrar os procedimentos de segurança. Por gentileza, fique atento mesmo que seja um cliente frequente. Em caso de despressurização, as máscaras de oxigênio cairão automaticamente: Puxe uma delas; Coloque-a sobre o nariz e a boca e puxe as tiras laterais para ajustar; Respire normalmente; Coloque primeiro a sua máscara e então ajude as pessoas com dificuldades. Luzes no teto e no piso indicarão o caminho para as (06/08) saídas de emergência: 02 portas na parte da frente; (02/04) saídas sobre as asas; 02 portas na parte de trás. Procure a saída mais próxima do seu assento. Ela pode estar atrás de você. Em uma emergência deixe toda a bagagem para sair da aeronave. Sempre que o aviso estiver aceso ou você estiver sentado, o cinto deve estar afivelado. Para afivelar seu cinto: Una as pontas; Puxe a lateral para ajustar e, para soltar, levante a parte superior da fivela. Leia o cartão com as instruções de segurança localizado no bolsão à sua frente. Em um pouso de emergência, fique em uma das posições indicadas neste cartão. Os conjuntos de sobrevivência estão localizados ao longo da aeronave e em caso de pouso na água, use o (assento da poltrona/colete salva-vidas) para flutuar. Desejamos a todos uma ótima viagem!', '', 'Preparémonos para el despegue. Deje el respaldo de su asiento en posición vertical y la mesilla cerrada. Esté atento a las señales luminosas para abrocharse el cinturón. Puede abrir el compartimiento superior cuando esta señal esté apagada. Está prohibido fumar en el avión y también impedir u intentar impedir el funcionamiento de los detectores de humo de los baños. Lea la tarjeta con instrucciones de seguridad ubicada en la bolsa delantera de sus asientos. En un aterrizaje de emergencia, adopte una de las posiciones indicadas en esta tarjeta y deje todo su equipaje para salir de la aeronave. ¡Les deseamos un buen viaje!', 130),
  ('alocucao-15', '4.10.1 Complementação da alocução Antes da Decolagem - Voos domésticos', 'Em caso de uma despressurização, se você estiver utilizando máscara protetora facial, deverá retirá-la antes de colocar a sua máscara de oxigênio. O uso dos equipamentos de flutuação está descrito no cartão de instruções de segurança.

Aeronaves com coletes salva-vidas: O colete salva-vidas está localizado (abaixo da sua poltrona / no compartimento acima, próximo a chamada de comissários).', 'We are preparing for takeoff! Please make sure your seat-back and tray tables are in their full upright position. Pay close attention to the lights to fasten your seatbelts. You can only open the overhead bins when this warning light is off. Smoking is not allowed aboard and tampering with or disabling the smoke detectors in the lavatories is prohibited by law. Please, read the card with the safety instructions located in the pocket in front of you. In an emergency landing, stay in one of the positions indicated on this card. In an emergency evacuation, leave all carry-on luggage in the aircraft. In case of decompression, if you are wearing a face mask, you should remove it before putting on your oxygen mask. The use of the flotation devices is described in the safety instruction card.

Aeronaves com coletes salva-vidas: The life vest is located (below your seat / in the compartment above, next to the flight attendant call) We wish you all a great flight!', 'En caso de descompresión, si lleva mascarilla, debe quitársela antes de ponerse la máscara de oxígeno. El uso de los dispositivos de flotación se describe en la tarjeta de instrucciones de seguridad.

Aeronaves com coletes salva-vidas: El chaleco salvavidas se encuentra (debajo de su / en el compartimento de arriba, junto a la llamada de tripulantes).', 140),
  ('alocucao-16', '4.11 ANTES DA DECOLAGEM - VOOS INTERNACIONAIS', 'Vamos nos preparar para a decolagem! Deixe o encosto da sua poltrona na posição vertical e sua mesa fechada e travada...', 'We are preparing for takeoff. Please, make sure your seat-back and tray tables are in their full upright position. Pay attention to the fasten seatbelt signs. You can only open the overhead bins when this warning light is off. Smoking is not allowed on board and tampering with or disabling the smoke detectors in the lavatories is prohibited. We will be showing our safety demonstration. Please, pay close attention, even if you are a frequent flyer. In the event of a decompression, oxygen masks will drop automatically: Pull a mask towards you; Place it over your nose and mouth, and adjust the elastic band around your head; Breathe normally; Put your own mask first, and only then assist someone else. Floor and ceiling lights will illuminate the aisle to guide you to (06/08) emergency exits: 02 doors at the front; (02/04) overwing exits; 02 doors at the rear. Look for the closest exit to you. It may be behind you. In an emergency evacuation, leave all your carry-on behind. Whenever the warning light is on or when you are seated, the seatbelt should be fastened. To fasten your seatbelt: Insert the metal fitting into the buckle; Tighten by pulling on the loose end of the strap, and to release your seatbelt, lift the top of the buckle. Read the card with the safety instructions located in the pocket in front of you. In an emergency landing, stay in one of the positions indicated on this card. Survival kits are located along the cabin, and in case of ditching use your (seat cushion/life vest) as a flotation device. We wish you all a great flight!', 'Preparémonos para el despegue. Deje el respaldo de su asiento en posición vertical...', 150),
  ('alocucao-17', '4.11.1 Complementação da alocução Antes da Decolagem - Voos Internacionais', 'Em caso de uma despressurização, se você estiver utilizando máscara protetora facial, deverá retirá-la antes de colocar a sua máscara de oxigênio. O uso dos equipamentos de flutuação está descrito no cartão de instruções de segurança.

Aeronaves com coletes salva-vidas: O colete salva-vidas está localizado (abaixo da sua poltrona / no compartimento acima, próximo a chamada de comissários).', 'In case of decompression, if you are wearing a face mask, you should remove it before putting on your oxygen mask. The use of the flotation devices is described in the safety instruction card.

Aeronaves com coletes salva-vidas: The life vest is located (below your seat/ in the compartment above, next to the flight attendant call)', 'En caso de descompresión, si lleva mascarilla, debe quitársela antes de ponerse la máscara de oxígeno. El uso de los dispositivos de flotación se describe en la tarjeta de instrucciones de seguridad.

Aeronaves com coletes salva-vidas: El chaleco salvavidas se encuentra (debajo de su / en el compartimento de arriba, junto a la llamada de tripulantes).', 160),
  ('alocucao-18', '4.12 ANTES DA DECOLAGEM - GRANDE EXTENSÃO DE ÁGUA', 'Vamos nos preparar para a decolagem! Deixe o encosto da sua poltrona na posição vertical e sua mesa fechada e travada...', 'We are preparing for takeoff. Please, make sure your seat-back and tray tables are in their full upright position. Pay attention to the fasten seatbelt signs. You can only open the overhead bins when this warning light is off. Smoking is not allowed on board and tampering with or disabling the smoke detectors in the lavatories is prohibited. We will be showing our safety demonstration. Please, pay close attention, even if you are a frequent flyer. In the event of a decompression, oxygen masks will drop automatically: Pull a mask towards you; Place it over your nose and mouth, and adjust the elastic band around your head; Breathe normally; Put your own mask first, and only then assist someone else. Floor and ceiling lights will illuminate the aisle to guide you to (06/08) emergency exits: 02 doors at the front; (02/04) overwing exits; 02 doors at the rear. Look for the closest exit to you. It may be behind you. In an emergency evacuation, leave all your carry-on behind. Whenever the warning light is on or when you are seated, the seatbelt should be fastened. To fasten your seatbelt: Insert the metal fitting into the buckle; Tighten by pulling on the loose end of the strap, and to release your seatbelt, lift the top of the buckle. Read the card with the safety instructions located in the pocket in front of you. In an emergency landing, stay in one of the positions indicated on this card. Survival kits are located along the cabin, and in case of a ditching, use your life vest that is located (below your seat / in the compartment above your head). To don your vest: Slip it over your head and adjust the strap around your waist. To inflate it, pull down on the red tab or blow into the tubes. Only inflate your life vest when leaving the aircraft. The life rafts are located in the compartments indicated by the flight attendants. We wish you all a great flight!', 'Preparémonos para el despegue...', 170),
  ('alocucao-19', '4.12.1 Complementação da alocução Antes da Decolagem- Grande Extensão de Água', 'Em caso de uma despressurização, se você estiver utilizando máscara protetora facial, deverá retirá-la antes de colocar a sua máscara de oxigênio.', 'In case of decompression, if you are wearing a face mask, you should remove it before putting on your oxygen mask.', 'En caso de descompresión, si lleva mascarilla, debe quitársela antes de ponerse la máscara de oxígeno.', 180),
  ('alocucao-20', '4.13 REDUÇÃO DE LUZES DA CABINE', 'Para o seu conforto, vamos diminuir as luzes da cabine.', 'For your comfort, we will dim the cabin lights.', 'Para su comodidad, reduciremos las luces de la cabina.', 190),
  ('alocucao-21', '4.14 REJEIÇÃO DE DECOLAGEM - RTO', 'O Comandante cancelou a decolagem e assim que possível, dará mais informações. Por gentileza, permaneça sentado com seu cinto afivelado. Obrigado(a).', 'The Captain has rejected takeoff and, as soon as possible, he will provide you with more information. Please remain seated with your seatbelt fastened. Thank you.', 'El Capitán ha rechazado el despegue y, tan pronto como sea posible, proporcionará más informaciones. Permanezca sentado con el cinturón de seguridad abrochado. ¡Gracias!', 200),
  ('alocucao-22', '4.15 RETORNO DA AERONAVE', 'Devido a/ao _______ (motivo informado pela tripulação técnica), precisamos retornar. Avisaremos assim que tivermos mais informações.', 'Due to (motivo), we need to return. We will provide you with further information as soon as possible.', 'Due to (motivo informado pela tripulação técnica), we need to return. We will provide you with further information as soon as possible.', 210),
  ('alocucao-23', '4.16 APÓS A DECOLAGEM DOMÉSTICO', 'Para a sua segurança, permaneça com o cinto afivelado durante todo o voo.

Com álcool em gel disponível: Disponibilizamos _______ (álcool em gel Giovanna Baby/ álcool em gel) próximo aos toaletes, localizados nas partes dianteira e traseira da aeronave.

Sem álcool em gel: Os toaletes estão localizados nas partes dianteira e traseira da aeronave.

Somente em aeronaves com tomada elétrica/USB abaixo do assento a partir da fileira 2: A (tomada elétrica/USB) para recarregar seu equipamento eletrônico está abaixo do seu assento.

Voos com água sob demanda: Para solicitar água, aperte o botão de chamada de comissários no painel superior. Conte conosco para um voo seguro e confortável.', '', '', 220),
  ('alocucao-24', '4.17 APÓS A DECOLAGEM - INTERNACIONAL', 'Para a sua segurança, permaneça com o cinto afivelado durante todo o voo.

Com álcool em gel disponível: Disponibilizamos _______ (álcool em gel Giovanna Baby/ álcool em gel) próximo aos toaletes, localizados nas partes dianteira e traseira da aeronave.

Sem álcool em gel disponível: Os toaletes estão localizados nas partes dianteira e traseira da aeronave.

Somente em aeronaves com tomada elétrica/USB abaixo do assento a partir da fileira 2: A (tomada elétrica/USB) para recarregar seu equipamento eletrônico está abaixo do seu assento. Conte conosco para um voo seguro e confortável.', 'For your safety, remain seated with your seat-belts fastened throughout the flight.

Com álcool em gel disponível: There is (Giovanna Baby hand sanitizer/hand sanitizer) available close to the toilets, located at the front and rear of the aircraft.

Sem álcool em gel disponível: Toilets are located at the front and rear of the aircraft.

Somente em aeronaves com tomada elétrica/USB abaixo do assento a partir da fileira 2: The (outlet/USB port) for recharging your electronic devices is located below your seat. Count on us for a safe and comfortable flight.', 'Por su seguridad, permanezca sentado con los cinturones de seguridad abrochados durante todo el vuelo.

Com álcool em gel disponível: Hay (Giovanna Baby desinfectante de manos) disponible cerca de los baños, situados en la parte delantera y la parte trasera de la aeronave.

Sem álcool em gel disponível: Los baños se encuentran en las partes delantera y trasera de la aeronave.

Somente em aeronaves com tomada elétrica/USB abaixo do assento a partir da fileira 2: El (enchufe/USB) para cargar sus dispositivos electrónicos está debajo de su asiento. Cuente con nosotros para un vuelo seguro y cómodo.', 230),
  ('alocucao-25', '4.18 PREENCHIMENTO DE FORMULÁRIOS - DISTRIBUIÇÃO NO VOO', 'Vamos distribuir os formulários exigidos para a entrada no país. Utilize caneta e letra de forma. Por determinação das autoridades locais, os formulários deverão estar preenchidos antes do pouso. Se precisar de ajuda fale com um dos comissários. Obrigado (a).

Voos com destino a Colômbia: Caso esteja transportando quantia igual ou superior a US$ 10.000, solicite o formulário de declaração.', 'We will now distribute the forms required for your entry into the country. Remember to complete them in ink and block letters before landing. If you need help, ask one of our flight attendants. Thank you!

Voos com destino a Colômbia: If you are carrying an amount equal to or exceeding US$ 10,000, please request a customs declaration form.', 'Ahora distribuiremos los formularios requeridos para su ingreso al país. Recuerde completarlos con tinta y letras mayúsculas antes de aterrizar. Si usted necesita ayuda, pregúntele a uno de nuestros tripulantes. ¡Gracias!

Voos com destino a Colômbia: En caso de que esté transportando una cantidad igual ó superior a US$ 10.000, solicite el formulario de declaración.', 240),
  ('alocucao-26', '4.19 PREENCHIMENTO DE FORMULÁRIOS - DISTRIBUIÇÃO NO CHECK-IN', 'Para a entrada no país, preencha os formulários distribuídos no check-in, com caneta e letras de forma. Se precisar de ajuda fale com um dos comissários. Obrigado (a).', 'Please remember to fill out the forms distributed at check-in that are required for your entry into the country. They have to be completed in ink and block letters before landing. If you need help, ask one of our flight attendants. Thank you!', 'Recuerde completar los formularios que se distribuyen en el check-in y que son obligatorios para su ingreso al país. Tienen que estar completados en tinta y con letras mayúsculas antes de aterrizar. Si necesita ajuda, pregunte a uno de nuestros tripulantes. ¡Gracias!', 250),
  ('alocucao-27', '4.20 SERVIÇO DE BORDO - VOOS DOMÉSTICOS - COM DISTRIBUIÇÃO DE SNACKS', 'Vamos iniciar o nosso Serviço de Bordo. Neste voo oferecemos _______ (snack salgado / snack doce), bebidas variadas e café.', '', '', 260),
  ('alocucao-28', '4.21 SERVIÇO DE BORDO - VOOS INTERNACIONAIS - CURTOS E MÉDIOS', 'Voos Curtos: Iniciaremos nosso serviço de bordo acompanhado de bebidas variadas, incluindo café.

Voos Médios: Iniciaremos nosso serviço de bordo acompanhado de bebidas variadas.', 'Voos Curtos: We will begin our inflight service with assorted beverages, including coffee.

Voos Médios: We will begin our inflight service with assorted beverages.', 'Voos Curtos: Empezaremos nuestro servicio a bordo acompañado de bebidas variadas, incluido el café.

Voos Médios: Empezaremos nuestro servicio a bordo acompañado de bebidas variadas.', 270),
  ('alocucao-29', '4.22 SERVIÇO DE BORDO - VOOS INTERNACIONAIS - LONGOS', 'Iniciaremos o nosso serviço de bordo. Neste voo ofereceremos _______ (café da manhã / almoço / jantar) e bebidas variadas.

Voo com 2 serviços: Antes do nosso pouso, vamos oferecer snacks. E se precisar, estamos à disposição durante todo o voo.

Antes do início do 2º serviço de bordo: Iniciaremos o nosso serviço de bordo. Oferecemos snacks e bebidas variadas, incluindo café.', 'We will begin our inflight service. On this flight we will serve (breakfast/lunch / dinner) and assorted beverages.

Voo com 2 serviços: Before our landing, we will offer snacks. If you need any help, our Flight attendants will be available during the entire flight.

Antes do início do 2º serviço de bordo: We will begin our inflight service. We offer snacks and assorted beverages, including coffee.', 'Empezaremos nuestro servicio a bordo. En este vuelo ofrecemos (desayuno / almuerzo / cena) y bebidas variadas.

Voo com 2 serviços: Antes de aterrizar, ofreceremos galletas. Si necesita ayuda, nuestros tripulantes están disponibles durante todo el vuelo.

Antes do início do 2º serviço de bordo: Empezaremos nuestro servicio a bordo. Ofrecemos galletas y bebidas variadas, incluido el café.', 280),
  ('alocucao-30', '4.23 CANCELAMENTO / INTERRUPÇÃO DO SERVIÇO DE BORDO', 'Devido a/ao _______ (motivo), o serviço de bordo _______ (está/será) _______ (cancelado/interrompido) e daremos continuidade assim que possível).', 'Due to (motivo), our inflight service (is now canceled / will be interrupted), and resumed as soon as possible.', 'Debido a (motivo), nuestro servicio a bordo (ahora está cancelado / será interrumpido) y continuaremos cuando sea posible.', 290),
  ('alocucao-31', '4.24 CINTOS ATADOS - APÓS RECOLHIMENTO DO SERVIÇO DE BORDO', 'Nós valorizamos a sua segurança, por isso permaneçam sentados com os cintos afivelados, mesmo que os avisos de atar cintos estejam apagados.', 'We value your safety, so please remain seated with your seatbelt fastened, even when the seatbelt sign is off.', 'Para su seguridad permanezca sentado con el cinturón de segurança abrochado, incluso cuando la señal del cinturón de seguridad está apagada.', 300),
  ('alocucao-32', '4.25 TURBULÊNCIA - AVISO DE ATAR CINTOS', 'Antes: Permaneça sentado com o cinto afivelado e não deixe nenhum objeto solto. Atravessaremos uma área de turbulência.

Durante: Permaneça sentado com o cinto afivelado e não deixe nenhum objeto solto. Estamos atravessando uma área de turbulência.', 'Antes: Please remain seated with your seatbelt fastened and hold your belongings. We will go through a turbulence area.

Durante: Please remain seated with your seatbelt fastened and hold your belongings. We are going through a turbulence area.', 'Antes: Permanezca sentado con el cinturón de seguridad abrochado y sujete sus pertenencias. Pasaremos por una zona de turbulencias.

Durante: Permanezca sentado con el cinturón de seguridad abrochado y sujete sus pertenencias. Estamos atravesando una zona de turbulencias.', 310),
  ('alocucao-33', '4.25.1 Complementação da alocução TURBULÊNCIA - AVISO DE ATAR CINTOS', 'O aviso de atar cintos é extensivo aos comissários. Atenderemos a(s) chamada(s) assim que o aviso for apagado.', 'This warning is for flight attendants as well. We will assist you as soon as the signs are off.', 'Este aviso también se aplica a los auxiliares de vuelo. Les asistiremos en cuanto se apaguen las señales luminosas.', 320),
  ('alocucao-34', '4.26 SOLICITAÇÃO DE MÉDICO VOLUNTÁRIO A BORDO', 'Sua atenção, por favor. Uma pessoa requer atendimento médico. Se houver um médico voluntário a bordo, apresente-se a um dos comissários com seu CRM em mãos. Obrigado(a).', 'Your attention please. A person is in need of volunteer medical assistance. If there is a volunteer doctor aboard, please present to one of the flight attendants with your medical ID. Thank you.', 'Su atención, por favor. Una persona necesita atención médica voluntaria. Si hay un médico voluntario a bordo, por favor presentarse a uno de los tripulantes de cabina con su identificación médica. ¡Gracias!', 330),
  ('alocucao-35', '4.27 SOLICITAÇÃO DE MÉDICO VETERINÁRIO VOLUNTÁRIO A BORDO', 'Sua atenção, por favor. Uma pessoa requer atendimento médico veterinário para seu Pet. Se houver um médico veterinário voluntário a bordo, apresente-se a um dos comissários com seu CRMV em mãos. Obrigado (a)!', 'Your attention, please. A person is in need of volunteer veterinary medical assistance for their pet. If there is a volunteer veterinarian aboard, present to one of the flight attendants with your medical ID. Thank you!', 'Su atención, por favor. Una persona necesita un médico veterinario voluntario para su mascota. Si hay un veterinario voluntario a bordo, presentarse a uno de los tripulantes de cabina con su identificación médica. ¡Gracias!', 340),
  ('alocucao-36', '4.28 PROIBIÇÃO DE DESEMBARQUE COM PRODUTOS ESPECÍFICOS', 'Por determinação das Autoridades locais, é proibida a entrada de animais, vegetais e seus produtos, sem autorização de importação e certificação aplicável. Se tiver algum destes itens, apresente-se à fiscalização no canal de Bens a Declarar, após retirar a sua bagagem. Obrigado(a).', 'By determination of the local Authorities, the entrance of any animal, plants and derivatives, without import authorization and the applicable certification, is prohibited. If you have any of these items, go through the Goods to Declare channel after picking up your luggage. Thank you.', 'Por determinación de las autoridades locales, la entrada de cualquier animal, planta y derivados, sin autorización de importación y la certificación aplicable, está prohibida. Si tiene alguno de estos artículos, vaya a la sección Productos a Declarar, después de recoger su equipaje. ¡Gracias!', 350),
  ('alocucao-37', '4.29 RECOLHIMENTO DE MATERIAIS - VOO DOMÉSTICO', 'Para o seu conforto, vamos recolher os materiais que possam ser descartados.', '', '', 360),
  ('alocucao-38', '4.30 RECOLHIMENTO DE MATERIAIS - VOO INTERNACIONAL', '-', '-', '-', 370),
  ('alocucao-39', '4.30.1 Voos sem manta', 'Para o seu conforto, vamos recolher os materiais que possam ser descartados.', 'For your comfort, we will now collect any disposable items.', 'Para su comodidad, ahora recogeremos cualquier artículo desechable.', 380),
  ('alocucao-40', '4.30.2 Voos com manta', 'Para o seu conforto, vamos recolher os materiais que possam ser descartados. As mantas devem ser deixados no assento antes do desembarque.', 'For your comfort, we will now collect any disposable items. Blankets should be left on the seats before deplaning.', 'Para su comodidad, ahora recogeremos cualquier artículo desechable. Las mantas deben dejarse en los asientos antes de desembarcar.', 390),
  ('alocucao-41', '4.31 CRUZAMENTO DA CORDILHEIRA', 'Em alguns instantes, vamos sobrevoar a Cordilheira dos Andes. Por ser um dos pontos mais altos das Américas, é possível que ocorra instabilidade. Para a sua segurança permaneça sentado com seu cinto afivelado.', 'In a few moments, we will fly over the Andes, the highest mountain range in South America. Therefore, some turbulence is expected. For your safety, please remain seated with your seatbelt fastened.', 'En algunos instantes, vamos a sobrevolar la Cordillera de los Andes. Por ser uno de los puntos más altos de las Américas, es posible que ocurra inestabilidad. Para su seguridad, permanezca sentado con su cinturón abrochado.', 400),
  ('alocucao-42', '4.31.1 Complementação da alocução CRUZAMENTO DA CORDILHEIRA', 'O aviso de atar cintos é extensivo aos comissários. Atenderemos a(s) chamada(s) assim que o aviso for apagado.', 'This warning is for flight attendants as well. We will assist you as soon as the signs are off.', 'Este aviso también se aplica a los auxiliares de vuelo. Les asistiremos en cuanto se apaguen las señales luminosas.', 410),
  ('alocucao-43', '4.32 PROIBIÇÃO TOTAL DE USO DE PEDS', '-', '-', '-', 420),
  ('alocucao-44', '4.32.1 Com suspeita ou confirmação de interferência', 'O Comandante pede a todos que desliguem seus equipamentos eletrônicos neste momento, pois detectou uma interferência. Nossa segurança também depende de você. Obrigado(a).', 'The Captain has requested that all electronic devices be turned off at this moment because some interference has been detected. Our safety depends on you too. Thank you.', 'El Capitán ha solicitado que todos los dispositivos electrónicos se apaguen en este momento porque se ha detectado alguna interferencia. Nuestra seguridad también depende de ti. ¡Gracias!', 430),
  ('alocucao-45', '4.32.2 Aproximação ILS CAT II', 'O Comandante pede a todos que desliguem seus equipamentos eletrônicos, pois o pouso será feito por meio de instrumentos de alta precisão. Nossa segurança também depende de você. Obrigado(a).', 'The Captain has requested that all electronic devices be turned off at this moment because we''ll be relying on precision instruments for our landing. Our safety depends on you, too. Thank you.', 'El Capitán ha solicitado que todos los dispositivos electrónicos se apaguen en este momento porque dependeremos de instrumentos de precisión para nuestro aterrizaje. Nuestra seguridad también depende de ti. ¡Gracias!', 440),
  ('alocucao-46', '4.33 ANTES DO POUSO', 'Diurno: Vamos nos preparar para o pouso! Coloque o encosto de sua poltrona na posição vertical, feche e trave sua mesa, afivele seu cinto e guarde os objetos pessoais de forma segura.

Noturno: Vamos nos preparar para o pouso! Coloque o encosto de sua poltrona na posição vertical, feche e trave sua mesa, afivele seu cinto e guarde os objetos pessoais de forma segura. Para o seu conforto, vamos diminuir as luzes da cabine.', 'Diurno: Let''s get ready for landing! Please make sure your seat-back and tray table are in their full upright position, fasten your seatbelt and keep your belongings safely stored.

Noturno: Let''s get ready for landing! Please make sure your seat-back and tray table are in their full upright position, fasten your seatbelt and keep your belongings safely stored. For your comfort, we will dim the cabin lights. Thank you.', 'Diurno: ¡Preparémonos para el aterrizaje! Por favor, asegúrese de que el respaldo de su asiento esté en la posición vertical y la mesilla completamente cerrada. Abróchese el cinturón de seguridad y mantenga sus pertenencias guardadas de forma segura. ¡Gracias!

Noturno: ¡Preparémonos para el aterrizaje! Por favor, asegúrese de que el respaldo de su asiento esté en la posición vertical y la mesilla completamente cerrada. Abróchese el cinturón de seguridad y mantenga sus pertenencias guardadas de forma segura. Para su comodidad, reduciremos las luces de la cabina. ¡Gracias!', 450),
  ('alocucao-47', '4.33.1 Complementação da alocução Antes do Pouso', 'Em uma emergência, deixe toda a bagagem para sair da aeronave.

Aeronaves com USB/Tomada: Pedimos que desconecte o seu equipamento eletrônico da (tomada/USB).

Aeronaves com USB/Tomada/Ped Holder: Pedimos que desconecte seu equipamento eletrônico da (tomada/USB) e feche o suporte da poltrona.', 'In an emergency evacuation, leave all your carry-on behind.

Aeronaves com USB/Tomada: We request that you unplug your electronic devices from the (outlet/USB port).

Aeronaves com USB/Tomada/Ped Holder: We request that you unplug your electronics device from the (outlet/USB port) and close the ped holder.', 'En una evacuación de emergencia, deje atrás todo su equipaje de mano.

Aeronaves com USB/Tomada: Desconecte su dispositivo electrónico del(a) (enchufe/USB.)

Aeronaves com USB/Tomada/Ped Holder: Desconecte su dispositivo electrónico del(a) (enchufe/ USB) y cierre el soporte.', 460),
  ('alocucao-48', '4.34 ANTES DO POUSO AEROPORTO ALTERNADO', 'Devido a/ao _______ (verificar a informação com a trip. técnica) vamos pousar em _______. Assim que possível, daremos mais informações. Obrigado(a).', 'Due to (verificar a informação com a trip. técnica) we are landing in _____. We will provide more information as soon as possible. Thank you.', 'Debido a (verificar a informação com a Tripulação Técnica) estamos aterrizando en _____. Proporcionaremos más informaciones lo antes posible. ¡Gracias!', 470),
  ('alocucao-49', '4.35 ANTES DO POUSO COM PARADA TÉCNICA', 'Dentro de instantes faremos uma parada em _______ para o reabastecimento da nossa aeronave e logo em seguida, continuaremos nossa viagem para _______.', 'We will make a quick stop for the refueling of the aircraft in _____, soon after, we will continue our trip to _____.', 'Haremos una parada rápida para el reabastecimiento de combustible de la aeronave en (nome da cidade), poco después, continuaremos nuestro viaje a (nome da cidade).', 480),
  ('alocucao-50', '4.36 INSPEÇÃO DE SECURITY - EUA COM ESCALA NA REP. DOMINICANA', 'Por determinação das Autoridades da República Dominicana, é obrigatória a inspeção de segurança de todas as aeronaves em voos internacionais. Será necessário que desembarquem e levem todos os seus objetos pessoais. Obrigado(a).', 'By determination of the Dominican Republic Authorities, security inspection is mandatory for all aircrafts on international flights. You will need to deplane and take all your belongings with you. Thank you.', 'Por orden de las autoridades de la República Dominicana, es obligatoria la inspección de seguridad de todas las aeronaves en vuelos internacionales. Será necesario que desembarquen y lleven consigo sus objetos personales. ¡Gracias!', 490),
  ('alocucao-51', '4.37 ARREMETIDA', 'O Comandante cancelou o pouso e, assim que possível, dará mais informações. Pedimos que continuem sentados com seus cintos afivelados. Obrigado(a)!', 'The Captain has canceled our landing. He will provide more information as soon as possible. Please remain seated with your seatbelt fastened. Thank you!', 'El capitán ha canceled nuestro aterrizaje. Proporcionará más informaciones tan pronto como sea posible. Permanezca sentado con el cinturón de seguridad abrochado. ¡Gracias!', 500),
  ('alocucao-52', '4.38 APÓS O POUSO - VOO DOMÉSTICO', 'Bem-vindos a (cidade). Permaneçam sentados, com os cintos de segurança afivelados até que os avisos de atar cintos se apaguem. Agradecemos por voarem conosco e por podermos trazê-los em segurança. São _______ ($h/min$) horário local...', '', '', 510),
  ('alocucao-53', '4.39 APÓS O POUSO - VOO INTERNACIONAL', 'Bem-vindos a (cidade). Permaneçam sentados, com os cintos de segurança afivelados até que os avisos de atar cintos se apaguem. Agradecemos por voar conosco e por podermos trazê-lo em segurança. São _______ ($h/min$) horário local...', 'Welcome to (cidade). Remain seated with your seatbelts fastened until the seatbelts signs have been turned off. We thank you for flying with us and bringing you safely. It is (AM/PM)...', 'Bienvenidos a (cidade). Permanezca sentado con los cinturones de seguridad abrochados hasta que se apaguen las señales luminosas. Gracias por volar con nosotros y traerte en seguridad...', 520),
  ('alocucao-54', '4.40 APÓS POUSO - AEROPORTO ALTERNADO OU PARADA TÉCNICA', 'Permaneça sentado, com seu cinto afivelado até que o avião esteja completamente estacionado e os avisos se apaguem. Daremos mais informações em breve. A partir de agora, você pode tirar do modo avião os seus equipamentos eletrônicos.', 'Please, remain seated with your seatbelt fastened until the signs have been switched off. We will provide more information as soon as possible. Now you can take your electronic device out of airplane mode.', 'Por favor, permanezca sentado con el cinturón de seguridad abrochado hasta que se hayan apagado las señales. Proporcionaremos más informaciones lo antes posible. Ahora usted puede sacar su dispositivo electrónico del modo avión.', 530),
  ('alocucao-55', '4.41 DESEMBARQUE - POR MEIO DE ESCADA - DIANTEIRA E/OU TRASEIRA', 'O seu desembarque será realizado por meio de escadas. Para sua segurança atente-se aos degraus. Clientes com necessidades de atendimento especial devem desembarcar pela porta dianteira da aeronave para o seu conforto. Obrigado (a).', 'You will deplane by stairs. For your safety, please watch your step. Thank you. For your comfort, Customers with special needs should deplane by the front door. Thank you.', 'Descenderás por escaleras. Por su segurança, por favor cuide sus pasos. Gracias. Para su comodidad, los clientes con necesidades especiales deben desembarcar por la puerta delantera. ¡Gracias!', 540),
  ('alocucao-56', '4.42 TROCA DE AERONAVE', 'Vamos trocar de aeronave. Por gentileza, desembarque levando todos os seus objetos pessoais. Se precisar, conte com a nossa equipe. Pedimos desculpas pelo incômodo. Obrigado(a).', 'Due to unexpected events, we will have to change aircraft. We request that you deplane with all your belongings. If you need any assistance, please refer to our staff. We apologize for the inconvenience. Thank you.', 'Debido a imprevistos, tendremos que cambiar de avión. Solicitamos que desembarque con todas tus pertenencias. Si necesita ayuda, por favor consulte a nuestro personal. Pedimos disculpas por las molestias. ¡Gracias!', 550),
  ('alocucao-57', '4.43 CONFERÊNCIA DE RECIBOS - NO DESEMBARQUE', 'Por determinação das Autoridades locais, todos que desembarcarem neste aeroporto deverão apresentar seu cartão de embarque após sair do aeronave. Obrigado(a).', 'As required by Local Authorities, every passenger deplaning at this airport must present their boarding pass after leaving the aircraft. Thank you.', 'Según lo requerido por las autoridades locales, todos los pasajeros que desembarquen en este aeropuerto deben presentar su tarjeta de embarque después (de salir) que salga del avión. ¡Gracias!', 560),
  ('alocucao-58', '4.44 CONFERÊNCIA DE RECIBOS - A BORDO', 'Verifique a numeração do seu assento em seu cartão de embarque, ele pode ter mudado para a continuação deste voo. A nossa equipe fará a conferência de todos a bordo. Para facilitar permaneça sentado com um documento de identificação em mãos. Obrigado(a).', 'Your seat may have changed for the next flight. Check the seat number on your boarding pass and change seats if necessary. Our staff will count all passengers aboard. To make this process easier, please remain seated and have your ID available. Thank you.', 'Es posible que su asiento haya cambiado para el próximo vuelo. Compruebe el número de asiento en su tarjeta de embarque y cambie de asiento si es necesario. Nuestro personal contará todos los pasajeros a bordo. Para facilitar este proceso, permanezca sentado y ten a mano tu identificación. ¡Gracias!', 570)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  body_pt = EXCLUDED.body_pt,
  body_en = EXCLUDED.body_en,
  body_es = EXCLUDED.body_es,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();